@startuml
participant User
participant Server
participant Database

User->>Server: Signup Request (Username, Password, email, number)
activate Server
alt Valid details
  Server->>Server: validate detials
  activate Database
  Server->>Database: Create User (Username, Password, email, number)
  alt Already User [code: 3]
    Database->>Server: User Found with same details
    Server->>User: Already user
  else Create user [code: 1]
    Database->>Server: New user [userID]
    Server->>User: User created
  deactivate Database
else Invalid details [code: 4]
  Server->>User: Invalid details
end
deactivate Server
@enduml